### PR TITLE
Support execute command configuration in ECS cluster config

### PR DESCRIPTION
**Pull request by hanscg**

### CODE REVIEW

**Review by FurqanHabibi — APPROVED** [review]
LGTM, once all checks are successful.

**Comment by hanscg** [comment]
Validation failed because `optional` was not a thing in Terraform 0.13 :orz:
Do I need to modify it to support 0.13 or is it acceptable to raise the minimum version to 0.14?

**Comment by FurqanHabibi** [comment]
Personally it's fine to increase to 0.14, @michaelaw320 ?

**Comment by michaelaw320** [comment]
I think it's fine to update minimum supported version to 0.14

**Comment by hanscg** [comment]
@michaelaw320 Do we need to bump major version?

**Comment by michaelaw320** [comment]
yes, let's bump it major

**Review by michaelaw320 — APPROVED** [review]

**Comment by hanscg** [comment]
`optional` was experimental until Terraform 1.3 :/
I think pushing the min version up to 1.3 is a bit too much, let me see if I can avoid `optional`.

**Comment by hanscg** [comment]
> What required the bump to 1.0?

The upgraded module in examples requires Terraform 1.0. 
I upgraded the modules because the old versions are not compatible with AWS provider version 5.
I couldn't find a middle ground - module version compatible with provider v5 but also compatible with Terraform 0.13.

Considering 1.0 has been around for 2 years I think it's time to bump the version too.

**Review by FurqanHabibi — APPROVED** [review]
LGTM, awesome work 💪

**Comment by hanscg** [comment]
@michaelaw320 Any objection to merging this?

**Review by michaelaw320 — APPROVED** [review]
LGTM, please merge and create new release

**Pull request merged**
